name: Performance Tests

on:
  push:
    branches: ["?"] # update later
  pull_request:
    branches: ["?"] # update later

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: "0.56.0"
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          flags: --out json=apps/performance/k6-report/bdd.json --compatibility-mode=experimental_enhanced
          path: apps/performance/src/bdd.ts
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: k6-bdd-results.json
          path: apps/performance/k6-report/bdd.json
          retention-days: 10
          overwrite: true # keep only fresh results
